import { projectsApi } from '../api/projects.api';
import { assetsApi } from '../api/assets.api';
import { materialsApi } from '../api/materials.compat.api';
import { scriptsApi } from '../api/scripts.api';
import { storyboardsApi } from '../api/storyboards.api';
import { creationApi } from '../api/creation.api';
import { generationTasksApi } from '../api/generationTasks.api';
import { inspirationApi } from '../api/inspiration.api';
import { scriptWorkflowTasksApi } from '../api/scriptWorkflowTasks.api';
import { authApi } from '../api/auth.api';
import { request } from '../api/http';

export { assetsApi, materialsApi, creationApi, generationTasksApi };

export const api = {
  getAuthStatus: authApi.status,
  loginWithArkKey: authApi.login,
  listProjects: projectsApi.list,
  createProject: projectsApi.create,
  updateProject: projectsApi.update,
  archiveProject: projectsApi.archive,
  listAssets: assetsApi.list,
  listGlobalAssets: assetsApi.listGlobal,
  getGlobalAsset: assetsApi.getGlobal,
  getGlobalAssetSlices: assetsApi.getGlobalSlices,
  getAsset: assetsApi.get,
  uploadAsset: assetsApi.upload,
  updateAsset: assetsApi.update,
  deleteAsset: assetsApi.remove,
  linkAssetToProject: assetsApi.link,
  unlinkAssetFromProject: assetsApi.unlink,
  deleteGlobalAsset: assetsApi.removeGlobal,
  searchAssets: assetsApi.search,
  recallAssets: assetsApi.recall,
  analyzeAsset: assetsApi.analyze,
  listAssetAnalysisTasks: assetsApi.listAnalysisTasks,
  getAssetAnalysisTask: assetsApi.getAnalysisTask,
  getAssetSlices: assetsApi.getSlices,
  listMaterials: materialsApi.list,
  uploadMaterial: assetsApi.upload,
  generateAsset: (projectId, payload) => request(`/projects/${projectId}/assets/generate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }),
  getAssetGenerationTask: (projectId, taskId) => request(`/projects/${projectId}/assets/generation-tasks/${taskId}`),
  reanalyzeAsset: assetsApi.analyze,
  getScript: scriptsApi.getCurrent,
  listScripts: scriptsApi.list,
  generateScript: scriptsApi.generate,
  saveScript: scriptsApi.save,
  refineScript: scriptsApi.refine,
  deleteScriptVersion: scriptsApi.deleteVersion,
  regenerateScript: scriptsApi.regenerate,
  regenerateScriptScene: scriptsApi.regenerateScene,
  getStoryboard: storyboardsApi.getCurrent,
  generateStoryboard: storyboardsApi.generate,
  saveStoryboard: storyboardsApi.save,
  updateStoryboardScene: storyboardsApi.updateScene,
  reorderStoryboardScenes: storyboardsApi.reorderScenes,
  deleteStoryboardScene: storyboardsApi.deleteScene,
  regenerateStoryboardScene: storyboardsApi.regenerateScene,
  deleteStoryboard: storyboardsApi.remove,
  createScriptWorkflowTask: scriptWorkflowTasksApi.create,
  listScriptWorkflowTasks: scriptWorkflowTasksApi.list,
  getScriptWorkflowTask: scriptWorkflowTasksApi.get,
  createEditingPlan: creationApi.createPlan,
  createSmartEditingPlan: creationApi.smartEdit,
  createOneClickVideo: creationApi.oneClick,
  renderCreation: creationApi.render,
  listCreationTasks: creationApi.listTasks,
  getCreationTask: creationApi.getTask,
  retryCreationTask: creationApi.retryTask,
  cancelCreationTask: creationApi.cancelTask,
  listCreationWorkflowTasks: creationApi.listWorkflowTasks,
  getCreationWorkflowTask: creationApi.getWorkflowTask,
  listTasks: generationTasksApi.list,
  createTask: generationTasksApi.create,
  retryTask: generationTasksApi.retry,
  searchInspirationVideos: inspirationApi.searchVideos,
  listInspirationVideos: inspirationApi.listVideos,
  clearInspirationVideos: inspirationApi.clearVideos,
  getInspirationVideo: inspirationApi.getVideo,
  analyzeInspirationVideo: inspirationApi.analyzeVideo,
  listInspirationTemplates: inspirationApi.listTemplates,
  generateInspirationTemplate: inspirationApi.generateTemplate,
  deleteInspirationTemplate: inspirationApi.deleteTemplate,
  analyzeAndTemplateInspirationVideos: inspirationApi.analyzeAndTemplate,
  listInspirationWorkflowTasks: inspirationApi.listWorkflowTasks,
  getInspirationWorkflowTask: inspirationApi.getWorkflowTask,
  listCrawlerTasks: inspirationApi.listCrawlerTasks,
  getCrawlerTask: inspirationApi.getCrawlerTask,
  cancelCrawlerTask: inspirationApi.cancelCrawlerTask,
};
